# Generated by Django 5.2.10 on 2026-09-05 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('cash', 'Cash Wallet'), ('bank', 'Bank Account'), ('card', 'Credit Card'), ('wallet', 'E-Wallet')], default='cash', max_length=20)),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('color', models.CharField(default='#1f7a70', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('user', 'name'), name='unique_account_per_user')],
            },
        ),
    ]
